In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
data1 = pd.read_csv("financial_risk_analysis_large.csv.zip")
data1

,CreditScore,AnnualIncome,LoanAmount,LoanDuration,Age,EmploymentStatus,MaritalStatus,NumberOfDependents,EducationLevel,HomeOwnershipStatus,...,JobTenure,MonthlySavings,AnnualBonuses,AnnualExpenses,MonthlyHousingCosts,MonthlyTransportationCosts,MonthlyFoodCosts,MonthlyHealthcareCosts,MonthlyEntertainmentCosts,LoanApproved
0,402,63295,18830,13,29,Self-Employed,Widowed,2,Doctorate,Other,...,24,378,3741,40058,977,412,399,136,124,0
1,735,55936,23729,1,42,Self-Employed,Divorced,3,Master,Own,...,10,575,4115,16745,695,206,898,252,131,0
2,570,62547,19660,7,54,Self-Employed,Single,3,Doctorate,Mortgage,...,16,691,4105,23273,627,266,392,73,36,0
3,406,46129,21674,23,25,Self-Employed,Divorced,3,High School,Other,...,6,452,4559,42163,397,307,250,378,-32,0
4,371,57725,12189,26,42,Employed,Widowed,4,Master,Own,...,2,690,7856,30087,723,315,114,88,68,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,414,83679,19053,10,54,Unemployed,Married,2,Bachelor,Other,...,33,523,5740,31540,890,351,599,148,138,0
999996,333,79096,22567,4,21,Self-Employed,Married,2,Bachelor,Rent,...,35,525,5669,26843,2082,80,427,366,100,0
999997,668,55138,13939,28,52,Employed,Divorced,0,Bachelor,Rent,...,20,386,3475,27936,393,-85,534,8,98,0
999998,627,62867,19115,8,23,Employed,Married,4,Associate,Mortgage,...,18,287,6476,17752,1226,311,227,119,167,0
999999,840,54393,20428,19,60,Self-Employed,Single,4,High School,Own,...,27,591,1958,35911,1069,361,500,244,198,0

In [5]:
data1['LoanApproved'].value_counts()

LoanApproved
0    626831
1    373169
Name: count, dtype: int64

In [7]:
data1['LoanPurpose'].value_counts()

LoanPurpose
Auto                  200291
Home                  200261
Education             200065
Debt Consolidation    199771
Other                 199612
Name: count, dtype: int64

In [9]:
data1.isnull().sum()

CreditScore                   0
AnnualIncome                  0
LoanAmount                    0
LoanDuration                  0
Age                           0
EmploymentStatus              0
MaritalStatus                 0
NumberOfDependents            0
EducationLevel                0
HomeOwnershipStatus           0
MonthlyDebtPayments           0
CreditCardUtilizationRate     0
NumberOfOpenCreditLines       0
NumberOfCreditInquiries       0
DebtToIncomeRatio             0
BankruptcyHistory             0
LoanPurpose                   0
PreviousLoanDefaults          0
InterestRate                  0
PaymentHistory                0
SavingsAccountBalance         0
CheckingAccountBalance        0
InvestmentAccountBalance      0
RetirementAccountBalance      0
EmergencyFundBalance          0
TotalAssets                   0
TotalLiabilities              0
NetWorth                      0
LengthOfCreditHistory         0
MortgageBalance               0
RentPayments                  0
AutoLoanBalance               0
PersonalLoanBalance           0
StudentLoanBalance            0
UtilityBillsPaymentHistory    0
HealthInsuranceStatus         0
LifeInsuranceStatus           0
CarInsuranceStatus            0
HomeInsuranceStatus           0
OtherInsurancePolicies        0
EmployerType                  0
JobTenure                     0
MonthlySavings                0
AnnualBonuses                 0
AnnualExpenses                0
MonthlyHousingCosts           0
MonthlyTransportationCosts    0
MonthlyFoodCosts              0
MonthlyHealthcareCosts        0
MonthlyEntertainmentCosts     0
LoanApproved                  0
dtype: int64

In [10]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 51 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   CreditScore                 1000000 non-null  int64
 1   AnnualIncome                1000000 non-null  int64
 2   LoanAmount                  1000000 non-null  int64
 3   LoanDuration                1000000 non-null  int64
 4   Age                         1000000 non-null  int64
 5   EmploymentStatus            1000000 non-null  object
 6   MaritalStatus               1000000 non-null  object
 7   NumberOfDependents          1000000 non-null  int64
 8   EducationLevel              1000000 non-null  object
 9   HomeOwnershipStatus         1000000 non-null  object
 10  MonthlyDebtPayments         1000000 non-null  int64
 11  CreditCardUtilizationRate   1000000 non-null  float64
 12  NumberOfOpenCreditLines     1000000 non-null  int64
 13  NumberOfCreditInquiries     1000000 non-null  int64
 14  DebtToIncomeRatio           1000000 non-null  float64
 15  BankruptcyHistory           1000000 non-null  int64
 16  LoanPurpose                 1000000 non-null  object
 17  PreviousLoanDefaults        1000000 non-null  int64
 18  InterestRate                1000000 non-null  float64
 19  PaymentHistory              1000000 non-null  int64
 20  SavingsAccountBalance       1000000 non-null  int64
 21  CheckingAccountBalance      1000000 non-null  int64
 22  InvestmentAccountBalance    1000000 non-null  int64
 23  RetirementAccountBalance    1000000 non-null  int64
 24  EmergencyFundBalance        1000000 non-null  int64
 25  TotalAssets                 1000000 non-null  int64
 26  TotalLiabilities            1000000 non-null  int64
 27  NetWorth                    1000000 non-null  int64
 28  LengthOfCreditHistory       1000000 non-null  int64
 29  MortgageBalance             1000000 non-null  int64
 30  RentPayments                1000000 non-null  int64
 31  AutoLoanBalance             1000000 non-null  int64
 32  PersonalLoanBalance         1000000 non-null  int64
 33  StudentLoanBalance          1000000 non-null  int64
 34  UtilityBillsPaymentHistory  1000000 non-null  float64
 35  HealthInsuranceStatus       1000000 non-null  object
 36  LifeInsuranceStatus         1000000 non-null  object
 37  CarInsuranceStatus          1000000 non-null  object
 38  HomeInsuranceStatus         1000000 non-null  object
 39  OtherInsurancePolicies      1000000 non-null  int64
 40  EmployerType                1000000 non-null  object
 41  JobTenure                   1000000 non-null  int64
 42  MonthlySavings              1000000 non-null  int64
 43  AnnualBonuses               1000000 non-null  int64
 44  AnnualExpenses              1000000 non-null  int64
 45  MonthlyHousingCosts         1000000 non-null  int64
 46  MonthlyTransportationCosts  1000000 non-null  int64
 47  MonthlyFoodCosts            1000000 non-null  int64
 48  MonthlyHealthcareCosts      1000000 non-null  int64
 49  MonthlyEntertainmentCosts   1000000 non-null  int64
 50  LoanApproved                1000000 non-null  int64
dtypes: float64(4), int64(37), object(10)
memory usage: 389.1+ MB

In [12]:
data1.describe()

,CreditScore,AnnualIncome,LoanAmount,LoanDuration,Age,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,NumberOfCreditInquiries,...,JobTenure,MonthlySavings,AnnualBonuses,AnnualExpenses,MonthlyHousingCosts,MonthlyTransportationCosts,MonthlyFoodCosts,MonthlyHealthcareCosts,MonthlyEntertainmentCosts,LoanApproved
count,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1.000000e+06,1000000.000000,1000000.000000,...,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000,1000000.000000
mean,574.559628,59971.227298,20001.643495,15.014402,43.497517,1.999334,499.712597,4.999768e-01,7.005118,4.501799,...,19.500790,499.097705,4999.802337,29990.070722,999.821493,299.567663,399.724339,199.424883,99.458080,0.373169
std,158.774753,15013.989902,5000.662270,8.363599,15.005348,1.415219,199.942646,2.885894e-01,4.318280,2.872479,...,11.541492,299.700808,1999.559754,9994.979331,400.084107,149.851337,199.959738,99.921983,49.931612,0.483647
min,300.000000,-9666.000000,-4900.000000,1.000000,18.000000,0.000000,-539.000000,5.038985e-07,0.000000,0.000000,...,0.000000,-937.000000,-3934.000000,-18396.000000,-1093.000000,-399.000000,-543.000000,-353.000000,-123.000000,0.000000
25%,437.000000,49855.000000,16630.000000,8.000000,30.000000,1.000000,365.000000,2.500684e-01,3.000000,2.000000,...,10.000000,297.000000,3650.000000,23246.000000,730.000000,198.000000,265.000000,132.000000,66.000000,0.000000
50%,574.000000,59973.000000,20006.000000,15.000000,43.000000,2.000000,499.000000,5.003170e-01,7.000000,5.000000,...,20.000000,499.000000,4999.000000,29998.000000,1000.000000,299.000000,400.000000,199.000000,99.000000,0.000000
75%,712.000000,70080.000000,23376.000000,22.000000,56.000000,3.000000,635.000000,7.497447e-01,11.000000,7.000000,...,29.000000,701.000000,6348.000000,36736.000000,1270.000000,401.000000,535.000000,267.000000,133.000000,1.000000
max,849.000000,132414.000000,44921.000000,29.000000,69.000000,4.000000,1504.000000,9.999982e-01,14.000000,9.000000,...,39.000000,2048.000000,14312.000000,79463.000000,2846.000000,1024.000000,1363.000000,670.000000,326.000000,1.000000

In [7]:
df = pd.DataFrame(data1)
df

,CreditScore,AnnualIncome,LoanAmount,LoanDuration,Age,EmploymentStatus,MaritalStatus,NumberOfDependents,EducationLevel,HomeOwnershipStatus,...,JobTenure,MonthlySavings,AnnualBonuses,AnnualExpenses,MonthlyHousingCosts,MonthlyTransportationCosts,MonthlyFoodCosts,MonthlyHealthcareCosts,MonthlyEntertainmentCosts,LoanApproved
0,402,63295,18830,13,29,Self-Employed,Widowed,2,Doctorate,Other,...,24,378,3741,40058,977,412,399,136,124,0
1,735,55936,23729,1,42,Self-Employed,Divorced,3,Master,Own,...,10,575,4115,16745,695,206,898,252,131,0
2,570,62547,19660,7,54,Self-Employed,Single,3,Doctorate,Mortgage,...,16,691,4105,23273,627,266,392,73,36,0
3,406,46129,21674,23,25,Self-Employed,Divorced,3,High School,Other,...,6,452,4559,42163,397,307,250,378,-32,0
4,371,57725,12189,26,42,Employed,Widowed,4,Master,Own,...,2,690,7856,30087,723,315,114,88,68,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
999995,414,83679,19053,10,54,Unemployed,Married,2,Bachelor,Other,...,33,523,5740,31540,890,351,599,148,138,0
999996,333,79096,22567,4,21,Self-Employed,Married,2,Bachelor,Rent,...,35,525,5669,26843,2082,80,427,366,100,0
999997,668,55138,13939,28,52,Employed,Divorced,0,Bachelor,Rent,...,20,386,3475,27936,393,-85,534,8,98,0
999998,627,62867,19115,8,23,Employed,Married,4,Associate,Mortgage,...,18,287,6476,17752,1226,311,227,119,167,0
999999,840,54393,20428,19,60,Self-Employed,Single,4,High School,Own,...,27,591,1958,35911,1069,361,500,244,198,0

In [14]:
numeric_df = df.select_dtypes(include = 'number')
numeric_df.corr()

,CreditScore,AnnualIncome,LoanAmount,LoanDuration,Age,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,NumberOfCreditInquiries,...,JobTenure,MonthlySavings,AnnualBonuses,AnnualExpenses,MonthlyHousingCosts,MonthlyTransportationCosts,MonthlyFoodCosts,MonthlyHealthcareCosts,MonthlyEntertainmentCosts,LoanApproved
CreditScore,1.000000,-0.000073,0.000173,0.000890,0.000747,0.001156,-0.000105,-0.002305,0.001172,0.000603,...,0.000364,-0.002186,-0.000546,0.000679,0.001275,-0.001408,0.000181,0.000274,-0.000380,0.486384
AnnualIncome,-0.000073,1.000000,0.001321,-0.001164,0.001681,-0.000778,0.002025,0.001518,-0.000968,-0.000841,...,-0.000701,-0.000669,-0.000445,-0.001263,0.000316,0.000941,0.000011,0.000686,-0.001696,0.043875
LoanAmount,0.000173,0.001321,1.000000,0.002114,0.001310,-0.000221,0.001404,-0.000722,0.001368,-0.001916,...,0.001180,-0.000804,-0.000720,0.000628,-0.000353,0.001123,-0.000037,0.000479,0.000044,0.001029
LoanDuration,0.000890,-0.001164,0.002114,1.000000,0.002273,-0.001137,-0.000084,-0.000459,0.001314,0.000609,...,0.000785,0.000869,0.001042,-0.001068,-0.001823,-0.002060,-0.001157,0.000585,0.000639,-0.000022
Age,0.000747,0.001681,0.001310,0.002273,1.000000,0.000873,-0.000544,-0.000570,0.001932,0.001662,...,-0.000671,0.000071,-0.001027,0.000709,-0.000881,0.000318,0.000864,-0.000007,0.000147,0.000021
NumberOfDependents,0.001156,-0.000778,-0.000221,-0.001137,0.000873,1.000000,0.002569,-0.002347,-0.000390,-0.001190,...,0.000310,-0.000284,0.000064,0.000527,-0.002077,0.000217,-0.000321,0.000141,-0.000128,0.000316
MonthlyDebtPayments,-0.000105,0.002025,0.001404,-0.000084,-0.000544,0.002569,1.000000,-0.001332,0.000352,-0.001015,...,-0.000554,0.000871,-0.001621,0.000451,0.000724,-0.000358,0.001648,-0.000351,-0.000473,-0.000556
CreditCardUtilizationRate,-0.002305,0.001518,-0.000722,-0.000459,-0.000570,-0.002347,-0.001332,1.000000,-0.002304,-0.001084,...,-0.000268,-0.000628,0.001777,-0.000869,0.000127,0.002046,-0.000710,-0.000783,-0.001821,-0.001545
NumberOfOpenCreditLines,0.001172,-0.000968,0.001368,0.001314,0.001932,-0.000390,0.000352,-0.002304,1.000000,0.000171,...,-0.001055,-0.000693,0.000613,0.000897,-0.000706,0.000484,-0.000413,0.001540,-0.002057,-0.000354
NumberOfCreditInquiries,0.000603,-0.000841,-0.001916,0.000609,0.001662,-0.001190,-0.001015,-0.001084,0.000171,1.000000,...,0.000163,-0.001411,0.001291,-0.000591,-0.000854,-0.000241,0.000078,0.000124,-0.000176,0.000577
DebtToIncomeRatio,-0.000693,-0.001419,0.000581,-0.000030,-0.001089,-0.000855,0.000728,0.000353,0.000633,0.001214,...,0.000152,-0.000323,-0.000472,0.000173,0.002044,0.000259,0.000660,0.002534,0.000887,-0.000417
BankruptcyHistory,0.000527,0.001010,-0.000554,-0.001358,0.000554,-0.001966,-0.000835,-0.000294,-0.000606,-0.001340,...,0.000124,0.000383,0.000911,0.000487,0.000189,0.001133,-0.000719,0.001578,-0.001320,0.000877
PreviousLoanDefaults,0.000342,0.001458,-0.000722,0.000280,0.001434,-0.000480,0.000301,-0.000745,0.000424,0.000605,...,0.000680,-0.000526,-0.002809,-0.001595,-0.000716,0.000627,-0.000969,-0.000894,-0.000067,-0.000031
InterestRate,0.000975,-0.000806,-0.000401,-0.000748,0.000116,-0.000128,-0.000804,0.000224,-0.000267,-0.000349,...,0.000695,0.001595,0.000684,-0.000144,0.000275,0.001654,0.000068,0.000474,0.000117,-0.000351
PaymentHistory,0.000007,-0.000013,-0.000540,0.001042,0.000287,-0.000952,-0.000458,-0.000022,-0.000278,-0.000492,...,0.000196,-0.000764,-0.000162,-0.000176,-0.000289,0.000723,0.000527,0.001593,0.000515,-0.001164
SavingsAccountBalance,0.000550,-0.001685,-0.002417,0.001633,0.000718,0.000339,0.000921,0.000053,-0.000877,0.000235,...,-0.000561,-0.000492,-0.001229,0.001571,0.000967,0.000260,-0.000729,-0.000320,0.001420,0.001135
CheckingAccountBalance,-0.000228,-0.000188,-0.000154,-0.000395,0.001810,-0.000111,0.000356,0.000883,0.001893,-0.001080,...,-0.000014,0.000605,0.000384,0.000746,-0.000455,-0.001134,0.000844,-0.000660,0.000244,-0.000590
InvestmentAccountBalance,-0.000385,-0.001083,0.000085,-0.000926,-0.000059,0.001132,-0.001050,-0.000680,-0.000539,-0.000753,...,0.001673,-0.001559,0.000678,0.000372,0.001077,0.000375,0.000400,-0.000744,0.001475,-0.001648
RetirementAccountBalance,0.001484,0.000246,0.002436,0.000111,0.000176,0.002319,0.001834,0.000767,0.000099,-0.002687,...,-0.000847,0.001573,0.000017,0.000464,0.002075,-0.001135,-0.000198,0.000141,-0.000219,-0.000206
EmergencyFundBalance,-0.000789,0.000127,-0.000379,0.000954,0.000487,0.001171,0.001360,0.000504,0.000808,-0.001007,...,-0.000135,-0.000587,0.000634,-0.000920,-0.000656,-0.000925,0.000681,-0.000074,-0.000481,0.000984
TotalAssets,0.000398,0.000494,-0.000596,-0.000250,0.000518,0.000543,-0.000808,0.000244,0.001657,-0.001603,...,0.000068,0.001181,-0.001077,-0.000217,0.000623,0.000989,0.000916,0.000523,-0.001564,0.001754
TotalLiabilities,-0.000651,-0.000268,0.001200,0.000321,0.000710,0.001177,-0.000601,0.001024,0.001836,-0.001349,...,-0.000988,-0.000381,-0.000342,0.000763,0.000245,0.000036,-0.000590,-0.002082,0.000111,0.000584
NetWorth,-0.000088,0.000645,-0.000018,-0.000608,0.000354,0.000058,0.001416,0.000242,-0.000915,-0.002109,...,-0.001202,0.002086,-0.001878,0.000095,-0.001383,0.001293,-0.000070,0.000960,0.001083,-0.001145
LengthOfCreditHistory,-0.002855,-0.000738,0.002752,-0.000495,-0.001315,-0.001215,-0.001442,-0.001072,-0.000212,-0.000953,...,-0.000332,0.000555,-0.001042,0.000483,-0.000115,-0.000316,0.001192,0.000303,-0.000426,-0.001831
MortgageBalance,0.001009,0.000258,0.001464,0.000086,0.000485,-0.000718,-0.000767,0.001376,-0.000305,-0.000430,...,0.001112,0.000247,-0.000117,-0.001005,-0.000176,-0.000582,-0.000258,-0.000783,0.000429,0.001318
RentPayments,0.000139,-0.001302,0.000059,-0.000582,0.000384,-0.000461,0.001250,-0.000027,-0.001361,-0.000671,...,-0.000898,0.000336,-0.000024,0.000139,-0.000359,0.000945,0.001217,-0.000063,-0.002132,-0.000506
AutoLoanBalance,0.000950,-0.000733,0.000410,0.001383,-0.001334,-0.001984,-0.001161,-0.000161,-0.001527,-0.001413,...,0.000586,0.000094,-0.000376,-0.000226,-0.001197,-0.001361,0.001143,0.000507,0.000146,-0.000454
PersonalLoanBalance,-0.001174,0.002910,-0.001059,0.000385,-0.002121,-0.000791,0.001599,-0.000049,0.000476,-0.000520,...,0.000847,0.000071,0.000652,0.000101,-0.000882,-0.002800,-0.000346,-0.000754,0.000793,-0.000652
StudentLoanBalance,0.000842,0.000104,0.001542,0.001718,-0.000373,0.001562,0.001181,0.001387,0.001639,-0.000280,...,-0.000127,0.000593,-0.000465,-0.000425,-0.001381,0.000199,-0.001432,0.000121,0.001186,0.000583
UtilityBillsPaymentHistory,0.000663,0.002597,0.000775,0.000048,-0.000467,0.000090,0.000409,0.000913,-0.000154,-0.002272,...,0.000836,-0.001128,-0.000086,-0.000760,0.000299,-0.000506,0.002426,-0.002248,-0.000200,0.000559
OtherInsurancePolicies,-0.000147,-0.001542,0.000120,0.001367,-0.001678,-0.000253,0.000298,-0.001336,-0.001158,0.001523,...,0.000090,-0.000426,0.000182,0.000383,0.000163,-0.000164,-0.001596,0.001161,-0.001312,-0.001252
JobTenure,0.000364,-0.000701,0.001180,0.000785,-0.000671,0.000310,-0.000554,-0.000268,-0.001055,0.000163,...,1.000000,0.001975,-0.000004,0.001056,-0.000983,-0.000495,0.002078,0.001808,-0.001487,0.000429
MonthlySavings,-0.002186,-0.000669,-0.000804,0.000869,0.000071,-0.000284,0.000871,-0.000628,-0.000693,-0.001411,...,0.001975,1.000000,0.001279,0.000423,0.001229,0.001187,0.000826,-0.000642,0.001173,-0.001776
AnnualBonuses,-0.000546,-0.000445,-0.000720,0.001042,-0.001027,0.000064,-0.001621,0.001777,0.000613,0.001291,...,-0.000004,0.001279,1.000000,0.002083,-0.000820,-0.000546,0.000948,0.000210,-0.000757,-0.000282
AnnualExpenses,0.000679,-0.001263,0.000628,-0.001068,0.000709,0.000527,0.000451,-0.000869,0.000897,-0.000591,...,0.001056,0.000423,0.002083,1.000000,-0.002234,-0.000317,0.001710,0.000644,-0.001272,0.001152
MonthlyHousingCosts,0.001275,0.000316,-0.000353,-0.001823,-0.000881,-0.002077,0.000724,0.000127,-0.000706,-0.000854,...,-0.000983,0.001229,-0.000820,-0.002234,1.000000,0.001352,-0.000052,-0.000166,-0.000653,-0.000141
MonthlyTransportationCosts,-0.001408,0.000941,0.001123,-0.002060,0.000318,0.000217,-0.000358,0.002046,0.000484,-0.000241,...,-0.000495,0.001187,-0.000546,-0.000317,0.001352,1.000000,-0.000509,0.000991,0.000656,0.000902
MonthlyFoodCosts,0.000181,0.000011,-0.000037,-0.001157,0.000864,-0.000321,0.001648,-0.000710,-0.000413,0.000078,...,0.002078,0.000826,0.000948,0.001710,-0.000052,-0.000509,1.000000,-0.000042,0.000481,0.000634
MonthlyHealthcareCosts,0.000274,0.000686,0.000479,0.000585,-0.000007,0.000141,-0.000351,-0.000783,0.001540,0.000124,...,0.001808,-0.000642,0.000210,0.000644,-0.000166,0.000991,-0.000042,1.000000,-0.000599,-0.000367
MonthlyEntertainmentCosts,-0.000380,-0.001696,0.000044,0.000639,0.000147,-0.000128,-0.000473,-0.001821,-0.002057,-0.000176,...,-0.001487,0.001173,-0.000757,-0.001272,-0.000653,0.000656,0.000481,-0.000599,1.000000,-0.000713
LoanApproved,0.486384,0.043875,0.001029,-0.000022,0.000021,0.000316,-0.000556,-0.001545,-0.000354,0.000577,...,0.000429,-0.001776,-0.000282,0.001152,-0.000141,0.000902,0.000634,-0.000367,-0.000713,1.000000

## Memory Optimization

In [17]:
df.memory_usage(deep=True).sum() / 1e6

896.67585

In [18]:
for col in df.select_dtypes(include='int'):
    df[col] = pd.to_numeric(df[col], downcast='integer')

for col in df.select_dtypes(include='float'):
    df[col] = pd.to_numeric(df[col], downcast='float')

In [13]:
df_sample = df.sample(100_000, random_state=42)

In [15]:
df_sample.describe(percentiles=[.01, .05, .95, .99])

,CreditScore,AnnualIncome,LoanAmount,LoanDuration,Age,NumberOfDependents,MonthlyDebtPayments,CreditCardUtilizationRate,NumberOfOpenCreditLines,NumberOfCreditInquiries,...,JobTenure,MonthlySavings,AnnualBonuses,AnnualExpenses,MonthlyHousingCosts,MonthlyTransportationCosts,MonthlyFoodCosts,MonthlyHealthcareCosts,MonthlyEntertainmentCosts,LoanApproved
count,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.00000,100000.000000
mean,574.137790,59941.510050,20020.235500,15.01219,43.537210,2.001070,499.358460,0.500579,7.004430,4.499000,...,19.497470,499.149540,4995.673020,29994.365840,1001.087190,300.122780,398.737020,199.176650,99.38202,0.371240
std,158.865941,15015.569415,4995.887781,8.37956,15.037308,1.414818,200.036514,0.288619,4.320634,2.872048,...,11.546731,300.390656,1994.173352,10025.270221,399.465207,150.187761,200.321558,99.755415,50.01626,0.483139
min,300.000000,-8954.000000,593.000000,1.00000,18.000000,0.000000,-385.000000,0.000030,0.000000,0.000000,...,0.000000,-771.000000,-3934.000000,-11810.000000,-665.000000,-393.000000,-518.000000,-221.000000,-107.00000,0.000000
1%,305.000000,25166.000000,8371.990000,1.00000,18.000000,0.000000,34.000000,0.009973,0.000000,0.000000,...,0.000000,-198.000000,380.990000,6651.990000,73.000000,-47.000000,-67.000000,-32.000000,-16.00000,0.000000
5%,327.000000,35273.000000,11804.900000,2.00000,20.000000,0.000000,170.000000,0.049282,0.000000,0.000000,...,1.000000,5.000000,1719.000000,13504.000000,345.000000,53.000000,70.000000,35.000000,17.00000,0.000000
50%,573.000000,59883.500000,20025.500000,15.00000,44.000000,2.000000,499.000000,0.502214,7.000000,4.000000,...,19.000000,499.000000,4999.000000,29971.000000,1001.000000,300.000000,398.000000,199.000000,99.00000,0.000000
95%,822.000000,84777.050000,28211.050000,28.00000,67.000000,4.000000,829.000000,0.949869,14.000000,9.000000,...,38.000000,992.000000,8280.050000,46435.000000,1657.000000,548.000000,728.000000,364.000000,182.00000,1.000000
99%,844.000000,95195.090000,31639.030000,29.00000,69.000000,4.000000,968.000000,0.989744,14.000000,9.000000,...,39.000000,1200.000000,9628.000000,53357.020000,1932.000000,648.000000,863.000000,431.000000,216.00000,1.000000
max,849.000000,121373.000000,41843.000000,29.00000,69.000000,4.000000,1379.000000,0.999983,14.000000,9.000000,...,39.000000,1920.000000,13366.000000,77236.000000,2745.000000,979.000000,1266.000000,653.000000,300.00000,1.000000

# Skewness and Outliers.

In [9]:
import pandas as pd
import numpy as np

def eda_stats_all_numeric(df, q_low=0.01, q_high=0.99):
    numeric_cols = df.select_dtypes(include=np.number).columns

    results = []

    for col in numeric_cols:
        series = df[col].dropna()

        outlier_ratio = (
            (series < series.quantile(q_low)) |
            (series > series.quantile(q_high))
        ).mean()

        results.append({
            "feature": col,
            "skewness": series.skew(),
            "zero_ratio": (series == 0).mean(),
            "outlier_ratio": outlier_ratio
        })

    return pd.DataFrame(results).sort_values(
        by="outlier_ratio", ascending=False
    )

In [17]:
eda_summary = eda_stats_all_numeric(df_sample)
eda_summary

                       feature  skewness  zero_ratio  outlier_ratio
20                 TotalAssets -0.001237     0.00000        0.02000
18    RetirementAccountBalance -0.006132     0.00002        0.02000
2                   LoanAmount -0.003355     0.00000        0.02000
26             AutoLoanBalance  0.014818     0.00001        0.02000
24             MortgageBalance  0.007653     0.00000        0.02000
29  UtilityBillsPaymentHistory -0.004231     0.00000        0.02000
7    CreditCardUtilizationRate -0.007142     0.00000        0.02000
21            TotalLiabilities -0.009778     0.00001        0.02000
10           DebtToIncomeRatio -0.001073     0.00000        0.02000
34              AnnualExpenses -0.000668     0.00000        0.02000
19        EmergencyFundBalance  0.019056     0.00010        0.02000
13                InterestRate -0.002791     0.00000        0.02000
28          StudentLoanBalance  0.012138     0.00000        0.02000
15       SavingsAccountBalance -0.002605     0.00008        0.02000
22                    NetWorth  0.006144     0.00002        0.01999
1                 AnnualIncome  0.014710     0.00000        0.01999
27         PersonalLoanBalance -0.005308     0.00004        0.01999
33               AnnualBonuses  0.004047     0.00004        0.01998
17    InvestmentAccountBalance -0.007667     0.00002        0.01997
16      CheckingAccountBalance -0.000571     0.00013        0.01997
35         MonthlyHousingCosts  0.001198     0.00013        0.01994
36  MonthlyTransportationCosts  0.002417     0.00078        0.01993
25                RentPayments  0.011198     0.00000        0.01991
6          MonthlyDebtPayments -0.002322     0.00022        0.01990
37            MonthlyFoodCosts  0.006084     0.00066        0.01989
32              MonthlySavings  0.003916     0.00059        0.01984
38      MonthlyHealthcareCosts  0.005818     0.00128        0.01960
39   MonthlyEntertainmentCosts  0.009427     0.00232        0.01930
0                  CreditScore  0.004968     0.00000        0.01768
23       LengthOfCreditHistory  0.000255     0.03351        0.00000
30      OtherInsurancePolicies  0.004238     0.19957        0.00000
31                   JobTenure  0.002628     0.02482        0.00000
14              PaymentHistory -0.002038     0.03361        0.00000
12        PreviousLoanDefaults  2.637751     0.89842        0.00000
11           BankruptcyHistory  4.126168     0.94993        0.00000
9      NumberOfCreditInquiries  0.002778     0.09914        0.00000
8      NumberOfOpenCreditLines  0.000350     0.06621        0.00000
5           NumberOfDependents -0.002400     0.20020        0.00000
4                          Age -0.000931     0.00000        0.00000
3                 LoanDuration  0.001126     0.00000        0.00000
40                LoanApproved  0.533025     0.62876        0.00000

In [19]:
eda_summary["needs_log"] = eda_summary["skewness"].abs() > 1
eda_summary["zero_inflated"] = eda_summary["zero_ratio"] > 0.3
eda_summary["many_outliers"] = eda_summary["outlier_ratio"] > 0.05

In [27]:
eda_summary

,feature,skewness,zero_ratio,outlier_ratio,needs_log,zero_inflated,many_outliers
20,TotalAssets,-0.001237,0.00000,0.02000,False,False,False
18,RetirementAccountBalance,-0.006132,0.00002,0.02000,False,False,False
2,LoanAmount,-0.003355,0.00000,0.02000,False,False,False
26,AutoLoanBalance,0.014818,0.00001,0.02000,False,False,False
24,MortgageBalance,0.007653,0.00000,0.02000,False,False,False
29,UtilityBillsPaymentHistory,-0.004231,0.00000,0.02000,False,False,False
7,CreditCardUtilizationRate,-0.007142,0.00000,0.02000,False,False,False
21,TotalLiabilities,-0.009778,0.00001,0.02000,False,False,False
10,DebtToIncomeRatio,-0.001073,0.00000,0.02000,False,False,False
34,AnnualExpenses,-0.000668,0.00000,0.02000,False,False,False
19,EmergencyFundBalance,0.019056,0.00010,0.02000,False,False,False
13,InterestRate,-0.002791,0.00000,0.02000,False,False,False
28,StudentLoanBalance,0.012138,0.00000,0.02000,False,False,False
15,SavingsAccountBalance,-0.002605,0.00008,0.02000,False,False,False
22,NetWorth,0.006144,0.00002,0.01999,False,False,False
1,AnnualIncome,0.014710,0.00000,0.01999,False,False,False
27,PersonalLoanBalance,-0.005308,0.00004,0.01999,False,False,False
33,AnnualBonuses,0.004047,0.00004,0.01998,False,False,False
17,InvestmentAccountBalance,-0.007667,0.00002,0.01997,False,False,False
16,CheckingAccountBalance,-0.000571,0.00013,0.01997,False,False,False
35,MonthlyHousingCosts,0.001198,0.00013,0.01994,False,False,False
36,MonthlyTransportationCosts,0.002417,0.00078,0.01993,False,False,False
25,RentPayments,0.011198,0.00000,0.01991,False,False,False
6,MonthlyDebtPayments,-0.002322,0.00022,0.01990,False,False,False
37,MonthlyFoodCosts,0.006084,0.00066,0.01989,False,False,False
32,MonthlySavings,0.003916,0.00059,0.01984,False,False,False
38,MonthlyHealthcareCosts,0.005818,0.00128,0.01960,False,False,False
39,MonthlyEntertainmentCosts,0.009427,0.00232,0.01930,False,False,False
0,CreditScore,0.004968,0.00000,0.01768,False,False,False
23,LengthOfCreditHistory,0.000255,0.03351,0.00000,False,False,False
30,OtherInsurancePolicies,0.004238,0.19957,0.00000,False,False,False
31,JobTenure,0.002628,0.02482,0.00000,False,False,False
14,PaymentHistory,-0.002038,0.03361,0.00000,False,False,False
12,PreviousLoanDefaults,2.637751,0.89842,0.00000,True,True,False
11,BankruptcyHistory,4.126168,0.94993,0.00000,True,True,False
9,NumberOfCreditInquiries,0.002778,0.09914,0.00000,False,False,False
8,NumberOfOpenCreditLines,0.000350,0.06621,0.00000,False,False,False
5,NumberOfDependents,-0.002400,0.20020,0.00000,False,False,False
4,Age,-0.000931,0.00000,0.00000,False,False,False
3,LoanDuration,0.001126,0.00000,0.00000,False,False,False
40,LoanApproved,0.533025,0.62876,0.00000,False,True,False

In [28]:
df.select_dtypes(include='object').nunique().sort_values(ascending=False)

EducationLevel           5
LoanPurpose              5
MaritalStatus            4
HomeOwnershipStatus      4
EmployerType             4
EmploymentStatus         3
HealthInsuranceStatus    2
LifeInsuranceStatus      2
CarInsuranceStatus       2
HomeInsuranceStatus      2
dtype: int64

# Missing Values Analysis

In [30]:
missing = df.isnull().mean().sort_values(ascending=False)
missing

CreditScore                   0.0
HomeInsuranceStatus           0.0
LengthOfCreditHistory         0.0
MortgageBalance               0.0
RentPayments                  0.0
AutoLoanBalance               0.0
PersonalLoanBalance           0.0
StudentLoanBalance            0.0
UtilityBillsPaymentHistory    0.0
HealthInsuranceStatus         0.0
LifeInsuranceStatus           0.0
CarInsuranceStatus            0.0
OtherInsurancePolicies        0.0
TotalLiabilities              0.0
EmployerType                  0.0
JobTenure                     0.0
MonthlySavings                0.0
AnnualBonuses                 0.0
AnnualExpenses                0.0
MonthlyHousingCosts           0.0
MonthlyTransportationCosts    0.0
MonthlyFoodCosts              0.0
MonthlyHealthcareCosts        0.0
MonthlyEntertainmentCosts     0.0
NetWorth                      0.0
TotalAssets                   0.0
AnnualIncome                  0.0
NumberOfOpenCreditLines       0.0
LoanAmount                    0.0
LoanDuration                  0.0
Age                           0.0
EmploymentStatus              0.0
MaritalStatus                 0.0
NumberOfDependents            0.0
EducationLevel                0.0
HomeOwnershipStatus           0.0
MonthlyDebtPayments           0.0
CreditCardUtilizationRate     0.0
NumberOfCreditInquiries       0.0
EmergencyFundBalance          0.0
DebtToIncomeRatio             0.0
BankruptcyHistory             0.0
LoanPurpose                   0.0
PreviousLoanDefaults          0.0
InterestRate                  0.0
PaymentHistory                0.0
SavingsAccountBalance         0.0
CheckingAccountBalance        0.0
InvestmentAccountBalance      0.0
RetirementAccountBalance      0.0
LoanApproved                  0.0
dtype: float64

# Target Variable Analysis

In [21]:
df['LoanApproved'].value_counts(normalize=True)   # Class imbalance.

LoanApproved
0    0.626831
1    0.373169
Name: proportion, dtype: float64

### Feature–Target Relationship (SELECTIVE)

In [34]:
df_sample.corr(numeric_only = True)['LoanApproved'].sort_values(ascending=False)

LoanApproved                  1.000000
CreditScore                   0.486513
AnnualIncome                  0.041866
MortgageBalance               0.008172
RentPayments                  0.007982
LoanAmount                    0.005775
LoanDuration                  0.004620
SavingsAccountBalance         0.003904
PreviousLoanDefaults          0.003902
PaymentHistory                0.003831
JobTenure                     0.003707
NumberOfDependents            0.003427
Age                           0.003344
TotalLiabilities              0.002807
RetirementAccountBalance      0.002772
NetWorth                      0.002627
AutoLoanBalance               0.002412
CheckingAccountBalance        0.002388
MonthlyHealthcareCosts        0.001472
OtherInsurancePolicies        0.001210
AnnualBonuses                 0.000529
MonthlySavings                0.000491
AnnualExpenses                0.000401
MonthlyHousingCosts           0.000302
MonthlyEntertainmentCosts     0.000256
TotalAssets                  -0.000020
UtilityBillsPaymentHistory   -0.000127
EmergencyFundBalance         -0.000196
PersonalLoanBalance          -0.000293
LengthOfCreditHistory        -0.000433
InterestRate                 -0.001083
CreditCardUtilizationRate    -0.001301
DebtToIncomeRatio            -0.002415
StudentLoanBalance           -0.002464
BankruptcyHistory            -0.002638
MonthlyFoodCosts             -0.002910
InvestmentAccountBalance     -0.003128
NumberOfCreditInquiries      -0.003285
NumberOfOpenCreditLines      -0.004855
MonthlyTransportationCosts   -0.005668
MonthlyDebtPayments          -0.008025
Name: LoanApproved, dtype: float64

In [64]:
categorical_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()
categorical_cols

['EmploymentStatus',
 'MaritalStatus',
 'EducationLevel',
 'HomeOwnershipStatus',
 'LoanPurpose',
 'HealthInsuranceStatus',
 'LifeInsuranceStatus',
 'CarInsuranceStatus',
 'HomeInsuranceStatus',
 'EmployerType']

In [36]:
df['EmploymentStatus']

0         Self-Employed
1         Self-Employed
2         Self-Employed
3         Self-Employed
4              Employed
              ...
999995       Unemployed
999996    Self-Employed
999997         Employed
999998         Employed
999999    Self-Employed
Name: EmploymentStatus, Length: 1000000, dtype: object

In [37]:
df['EducationLevel'].value_counts()

EducationLevel
Associate      200684
Master         200353
High School    200019
Bachelor       199831
Doctorate      199113
Name: count, dtype: int64

In [38]:
df['HomeOwnershipStatus']

0            Other
1              Own
2         Mortgage
3            Other
4              Own
            ...
999995       Other
999996        Rent
999997        Rent
999998    Mortgage
999999         Own
Name: HomeOwnershipStatus, Length: 1000000, dtype: object

In [39]:
df['LoanPurpose']

0                  Education
1         Debt Consolidation
2                      Other
3                       Home
4                  Education
                 ...
999995                  Home
999996    Debt Consolidation
999997                  Auto
999998                  Auto
999999                 Other
Name: LoanPurpose, Length: 1000000, dtype: object

In [40]:
df['HealthInsuranceStatus']

0           Insured
1         Uninsured
2         Uninsured
3           Insured
4           Insured
            ...
999995    Uninsured
999996    Uninsured
999997    Uninsured
999998      Insured
999999    Uninsured
Name: HealthInsuranceStatus, Length: 1000000, dtype: object

In [41]:
df['LifeInsuranceStatus']

0           Insured
1         Uninsured
2           Insured
3         Uninsured
4           Insured
            ...
999995      Insured
999996    Uninsured
999997    Uninsured
999998      Insured
999999    Uninsured
Name: LifeInsuranceStatus, Length: 1000000, dtype: object

In [42]:
df['EmployerType']

0         Self-Employed
1               Private
2                 Other
3                Public
4                 Other
              ...
999995            Other
999996            Other
999997            Other
999998    Self-Employed
999999           Public
Name: EmployerType, Length: 1000000, dtype: object

In [23]:
ordinal_col = ['EducationLevel']

onehot_cols = [
    'EmploymentStatus',
    'HomeOwnershipStatus',
    'LoanPurpose',
    'HealthInsuranceStatus',
    'LifeInsuranceStatus',
    'CarInsuranceStatus',
    'HomeInsuranceStatus',
    'EmployerType'
]

In [25]:
from sklearn.preprocessing import OrdinalEncoder

education_order = [
    ['High School', 'Bachelor', 'Master', 'Associate','Doctorate']
]

ordinal_encoder = OrdinalEncoder(categories=education_order)

df['EducationLevel_ordinal'] = ordinal_encoder.fit_transform(
    df[['EducationLevel']]
)

In [27]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

ohe = OneHotEncoder(
    drop='first',          # avoids dummy variable trap
    sparse_output=False,
    handle_unknown='ignore'
)

ohe_array = ohe.fit_transform(df_sample[onehot_cols])

ohe_df = pd.DataFrame(
    ohe_array,
    columns=ohe.get_feature_names_out(onehot_cols),
    index=df.index
)

In [29]:
df_encoded = pd.concat(
    [df.drop(columns=onehot_cols + ordinal_col), ohe_df],
    axis=1
)

In [72]:
df_encoded.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 59 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   CreditScore                      1000000 non-null  int16
 1   AnnualIncome                     1000000 non-null  int32
 2   LoanAmount                       1000000 non-null  int32
 3   LoanDuration                     1000000 non-null  int8
 4   Age                              1000000 non-null  int8
 5   MaritalStatus                    1000000 non-null  object
 6   NumberOfDependents               1000000 non-null  int8
 7   MonthlyDebtPayments              1000000 non-null  int16
 8   CreditCardUtilizationRate        1000000 non-null  float32
 9   NumberOfOpenCreditLines          1000000 non-null  int8
 10  NumberOfCreditInquiries          1000000 non-null  int8
 11  DebtToIncomeRatio                1000000 non-null  float32
 12  BankruptcyHistory                1000000 non-null  int8
 13  PreviousLoanDefaults             1000000 non-null  int8
 14  InterestRate                     1000000 non-null  float32
 15  PaymentHistory                   1000000 non-null  int8
 16  SavingsAccountBalance            1000000 non-null  int16
 17  CheckingAccountBalance           1000000 non-null  int16
 18  InvestmentAccountBalance         1000000 non-null  int32
 19  RetirementAccountBalance         1000000 non-null  int32
 20  EmergencyFundBalance             1000000 non-null  int16
 21  TotalAssets                      1000000 non-null  int32
 22  TotalLiabilities                 1000000 non-null  int32
 23  NetWorth                         1000000 non-null  int32
 24  LengthOfCreditHistory            1000000 non-null  int8
 25  MortgageBalance                  1000000 non-null  int32
 26  RentPayments                     1000000 non-null  int16
 27  AutoLoanBalance                  1000000 non-null  int32
 28  PersonalLoanBalance              1000000 non-null  int16
 29  StudentLoanBalance               1000000 non-null  int32
 30  UtilityBillsPaymentHistory       1000000 non-null  float32
 31  OtherInsurancePolicies           1000000 non-null  int8
 32  JobTenure                        1000000 non-null  int8
 33  MonthlySavings                   1000000 non-null  int16
 34  AnnualBonuses                    1000000 non-null  int16
 35  AnnualExpenses                   1000000 non-null  int32
 36  MonthlyHousingCosts              1000000 non-null  int16
 37  MonthlyTransportationCosts       1000000 non-null  int16
 38  MonthlyFoodCosts                 1000000 non-null  int16
 39  MonthlyHealthcareCosts           1000000 non-null  int16
 40  MonthlyEntertainmentCosts        1000000 non-null  int16
 41  LoanApproved                     1000000 non-null  int8
 42  EducationLevel_ordinal           1000000 non-null  float64
 43  EmploymentStatus_Self-Employed   1000000 non-null  float64
 44  EmploymentStatus_Unemployed      1000000 non-null  float64
 45  HomeOwnershipStatus_Other        1000000 non-null  float64
 46  HomeOwnershipStatus_Own          1000000 non-null  float64
 47  HomeOwnershipStatus_Rent         1000000 non-null  float64
 48  LoanPurpose_Debt Consolidation   1000000 non-null  float64
 49  LoanPurpose_Education            1000000 non-null  float64
 50  LoanPurpose_Home                 1000000 non-null  float64
 51  LoanPurpose_Other                1000000 non-null  float64
 52  HealthInsuranceStatus_Uninsured  1000000 non-null  float64
 53  LifeInsuranceStatus_Uninsured    1000000 non-null  float64
 54  CarInsuranceStatus_Uninsured     1000000 non-null  float64
 55  HomeInsuranceStatus_Uninsured    1000000 non-null  float64
 56  EmployerType_Private             1000000 non-null  float64
 57  EmployerType_Public              1000000 non-null  float64
 58  EmployerType_Self-Employed       1000000 non-null  float64
dtypes: float32(4), float64(17), int16(14), int32(11), int8(12), object(1)
memory usage: 232.7+ MB

## Model_Training

In [33]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [35]:
# Features and target
X = df_encoded.drop(columns=['LoanApproved','MaritalStatus'])
y = df_encoded['LoanApproved']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

In [132]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
from sklearn.decomposition import PCA

# Features and target
X = df_encoded.drop(columns=['LoanApproved','MaritalStatus'])
y = df_encoded['LoanApproved']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('pca', PCA(n_components=0.95)),  # keep 95% variance
    ('logreg', LogisticRegression(
        max_iter=2000,
        class_weight='balanced'
    ))
])

pipeline.fit(X_train, y_train)
y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

ROC-AUC: 0.7792567957851952
Accuracy: 0.70607
[[87277 38089]
 [20697 53937]]
              precision    recall  f1-score   support

           0       0.81      0.70      0.75    125366
           1       0.59      0.72      0.65     74634

    accuracy                           0.71    200000
   macro avg       0.70      0.71      0.70    200000
weighted avg       0.73      0.71      0.71    200000

In [74]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

X = df_encoded.drop(columns=['LoanApproved','MaritalStatus'])
y = df_encoded['LoanApproved']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

pipeline = Pipeline([
    ('scaler', StandardScaler()),
    ('log_reg', LogisticRegression(
        max_iter=20000,
        class_weight='balanced',   #useful for imbalanced class.
        solver='saga',
        n_jobs=-1
    ))
])

pipeline.fit(X_train, y_train)

y_pred = pipeline.predict(X_test)
y_proba = pipeline.predict_proba(X_test)[:, 1]

print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

ROC-AUC: 0.7920980752070454
Accuracy: 0.708405
[[87707 37659]
 [20660 53974]]
              precision    recall  f1-score   support

           0       0.81      0.70      0.75    125366
           1       0.59      0.72      0.65     74634

    accuracy                           0.71    200000
   macro avg       0.70      0.71      0.70    200000
weighted avg       0.73      0.71      0.71    200000

In [ ]:
!pip install xgboost

In [45]:
import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score, classification_report

# Features and target
X = df_encoded.drop(columns=['LoanApproved','MaritalStatus'])
y = df_encoded['LoanApproved']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42
)

# XGBoost classifier
xgb_model = xgb.XGBClassifier(
    n_estimators=700,
    learning_rate=0.03,
    max_depth=7,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    scale_pos_weight=(y_train == 0).sum() / (y_train == 1).sum()  # handles imbalance
)

# Train.
xgb_model.fit(X_train, y_train)

# Predict.
y_pred = xgb_model.predict(X_test)
y_proba = xgb_model.predict_proba(X_test)[:, 1]

# Evaluation.
print("ROC-AUC:", roc_auc_score(y_test, y_proba))
print("Accuracy:", accuracy_score(y_test, y_pred))

print(classification_report(y_test, y_pred))

ROC-AUC: 0.8007276623462052
Accuracy: 0.75203
              precision    recall  f1-score   support

           0       1.00      0.60      0.75    125366
           1       0.60      1.00      0.75     74634

    accuracy                           0.75    200000
   macro avg       0.80      0.80      0.75    200000
weighted avg       0.85      0.75      0.75    200000

In [55]:
from sklearn.metrics import precision_score, recall_score
from sklearn.metrics import precision_recall_curve, auc
import matplotlib.pyplot as plt

In [57]:
y_pred1 =xgb_model.predict(X_test)
y_scores = xgb_model.predict_proba(X_test)[:,1]

# Precision and Recall
precision = precision_score(y_test, y_pred1)
recall = recall_score(y_test, y_pred1)

print("Precision:", precision)
print("Recall:", recall)

Precision: 0.6008327561490263
Recall: 0.9995846397084439

In [61]:
precision_vals, recall_vals, thresholds = precision_recall_curve(y_test, y_scores)

In [63]:
pr_auc = auc(recall_vals, precision_vals)
print("PR-AUC:", pr_auc)

PR-AUC: 0.598238961016605